version: '3.3'

services:
    jobe:
        build:
            context: jobe
            args:
                - ROOTPASS=$ROOTPASS
                - TZ=$TZ
        env_file: .env
        environment: 
            - MYSQLUSER=$MYSQLUSER
            - MYSQLPASS=$MYSQLPASS
        container_name: jobe
        restart: unless-stopped
        networks:
            - inside
        depends_on: nginx
        # ports:
        #     - 4000:80
        #     - 3000-3100:3000-3100
        volumes:
            - mysqlVolume:/var/lib/mysql
    shiny:
        build:
            context: learnr
            args:
                - JOBE_IP=$JOBE_IP
        env_file: .env
        container_name: shiny
        restart: unless-stopped
        networks:
            - inside
        depends_on: nginx
        # ports:
        #     - 3838:3838
    nginx:
        context: nginx
    # image: nginx:stable
        container_name: nginx
        restart: unless-stopped
        ports:
            - 4000:80
            - 3000-3100:80
            - 3838:81
        networks:
            - inside
            - outside

volumes:
  mysqlVolume: {}

networks: 
    inside: 
        internal: true
    outside: {}